<?xml version="1.0" encoding="UTF-8" ?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsp="http://www.w3.org/ns/ws-policy/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <types>
        <xsd:schema>
            <xsd:import namespace="http://soap.tks.p.lodz.pl/users" schemaLocation="ClientAPI1.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://soap.tks.p.lodz.pl/" schemaLocation="ClientAPI2.xsd"/>
        </xsd:schema>
    </types>
    <message name="getUsersCount">
        <part name="parameters" element="tns:getUsersCount"/>
    </message>
</definitions>